name: Deploy to ECR

on:
 
  push:
    branches: [ master ]

env:
 # ECR_REPOSITORY: flask-app
 # EKS_CLUSTER_NAME: Kubernetes-demo 
  AWS_REGION: us-east-1

jobs:
  infra:
   steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_REGION}}

    - name: provision infrastructure using terraform code
      run:  cd cluster/ && terraform apply -auto-approve
